### ISSUE TITLE
vllm 模型（model/CodeLlama-34b-Instruct-hf）加速 GPUS=3,4 NUM_GPUs=2 设置无效

### ISSUE THREAD

**Issue by liyoung1992** [xusenlinzy/api-for-open-llm#117]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

启动命令 | Startup command

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

API_PREFIX=/v1

# vllm related
USE_VLLM=true
TRUST_REMOTE_CODE=true
TOKENIZE_MODE=slow
TENSOR_PARALLEL_SIZE=1
DTYPE=half

DEVICE=cuda
DEVICE_MAP=
GPUS=5，6，7
NUM_GPUs=3
~                                                                                                                                                                             
~                

export NCCL_IB_DISABLE=1; export NCCL_P2P_DISABLE=1; NCCL_DEBUG=INFO  CUDA_VISIBLE_DEVICES=5,6,7  python server.py

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

dtco0gpu1:217180:217314 [0] NCCL INFO Connected all rings
dtco0gpu1:217180:217314 [0] NCCL INFO Connected all trees
dtco0gpu1:217180:217314 [0] NCCL INFO 32 coll channels, 32 p2p channels, 32 p2p channels per peer
dtco0gpu1:217180:217314 [0] NCCL INFO comm 0x559cc4ffa060 rank 0 nranks 1 cudaDev 0 busId 3e000 - Init COMPLETE
Traceback (most recent call last):
  File workspace/llm/api-for-open-llm-master/server.py", line 2, in <module>
    from api.models import EMBEDDED_MODEL, GENERATE_MDDEL, app, VLLM_ENGINE
  File "workspace/llm/api-for-open-llm-master/api/models.py", line 139, in <module>
    VLLM_ENGINE = create_vllm_engine() if (config.USE_VLLM and config.ACTIVATE_INFERENCE) else None
  File "/workspace/llm/api-for-open-llm-master/api/models.py", line 97, in create_vllm_engine
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/miniconda3/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 442, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/miniconda3/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 250, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/miniconda3/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 279, in _init_engine
    return engine_class(*args, **kwargs)
  File "/miniconda3/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 102, in __init__
    self._init_workers(distributed_init_method)
  File "//miniconda3/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 134, in _init_workers
    self._run_workers(
  File "/miniconda3/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 678, in _run_workers
    output = executor(*args, **kwargs)
  File "//miniconda3/lib/python3.9/site-packages/vllm/worker/worker.py", line 67, in init_model
    self.model = get_model(self.model_config)
  File "//miniconda3/lib/python3.9/site-packages/vllm/model_executor/model_loader.py", line 58, in get_model
    model = model_class(model_config.hf_config)
  File "//miniconda3/lib/python3.9/site-packages/vllm/model_executor/models/llama.py", line 243, in __init__
    self.model = LlamaModel(config)
  File "/miniconda3/lib/python3.9/site-packages/vllm/model_executor/models/llama.py", line 207, in __init__
    self.layers = nn.ModuleList([
  File "/mminiconda3/lib/python3.9/site-packages/vllm/model_executor/models/llama.py", line 208, in <listcomp>
    LlamaDecoderLayer(config) for _ in range(config.num_hidden_layers)
  File "/miniconda3/lib/python3.9/site-packages/vllm/model_executor/models/llama.py", line 158, in __init__
    self.mlp = LlamaMLP(
  File "/miniconda3/lib/python3.9/site-packages/vllm/model_executor/models/llama.py", line 60, in __init__
    self.gate_up_proj = ColumnParallelLinear(hidden_size,
  File "/miniconda3/lib/python3.9/site-packages/vllm/model_executor/parallel_utils/tensor_parallel/layers.py", line 271, in __init__
    self.weight = Parameter(torch.empty(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 688.00 MiB (GPU 0; 9.78 GiB total capacity; 5.94 GiB already allocated; 421.31 MiB free; 5.95 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
dtco0gpu1:217180:217315 [0] NCCL INFO [Service thread] Connection closed by localRank 0
dtco0gpu1:217180:217180 [0] NCCL INFO comm 0x559cc4ffa060 rank 0 nranks 1 cudaDev 0 busId 3e000 - Abort COMPLETE

**Comment by xusenlinzy** [comment]
vllm使用TENSOR_PARALLEL_SIZE参数设置GPU数量
