### ISSUE TITLE
示例中的/examples/qwen-7b-chat/quad_calculator.py无法使用

### ISSUE THREAD

**Issue by maozhijie** [xusenlinzy/api-for-open-llm#119]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

其他问题 | Other issues

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

```
python examples/qwen-7b-chat/quad_calculator.py
```

### Dependencies

```

(apiopenllm) [root@t-gcgs-gpu-svr api-for-open-llm-master]# pip list | grep -E 'transformers|peft|torch'
peft                          0.5.0
sentence-transformers         2.2.2
torch                         2.0.1+cu118
torchaudio                    2.0.2+cu118
torchvision                   0.15.2+cu118
transformers                  4.33.0
transformers-stream-generator 0.0.4

```

### 运行日志或截图 | Runtime logs or screenshots

```
(apiopenllm) [root@t-gcgs-gpu-svr api-for-open-llm-master]# python examples/qwen-7b-chat/quad_calculator.py python examples/qwen-7b-chat/quad_calculator.py
2023-09-13 17:28:37.819 | INFO     | __main__:run:91 - Function call: {
  "name": "calculate_quad",
  "arguments": "{\"formula_str\": \"x**2\", \"a\": \"0.0\", \"b\": \"5.0\"}",
  "thought": "\u9700\u8981\u4f7f\u7528calculate_quad\u6765\u8ba1\u7b97\u5b9a\u79ef\u5206\uff0c\u5e76\u4f7f\u7528calculate_sqrt\u6765\u8ba1\u7b97\u5e73\u65b9\u6839\u3002"
}
2023-09-13 17:28:37.819 | INFO     | __main__:run:102 - Function args: {'formula_str': 'x**2', 'a': '0.0', 'b': '5.0'}
2023-09-13 17:28:37.820 | INFO     | __main__:run:108 - Function response: 41.66666666666666
Traceback (most recent call last):
  File "/root/anaconda3/envs/apiopenllm/lib/python3.9/site-packages/openai/api_requestor.py", line 403, in handle_error_response
    error_data = resp["error"]
KeyError: 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/pycode/api-for-open-llm-master/examples/qwen-7b-chat/quad_calculator.py", line 133, in <module>
    answer = calculator.run(query)
  File "/data/pycode/api-for-open-llm-master/examples/qwen-7b-chat/quad_calculator.py", line 120, in run
    response = openai.ChatCompletion.create(
  File "/root/anaconda3/envs/apiopenllm/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/root/anaconda3/envs/apiopenllm/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/root/anaconda3/envs/apiopenllm/lib/python3.9/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/root/anaconda3/envs/apiopenllm/lib/python3.9/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/root/anaconda3/envs/apiopenllm/lib/python3.9/site-packages/openai/api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
  File "/root/anaconda3/envs/apiopenllm/lib/python3.9/site-packages/openai/api_requestor.py", line 405, in handle_error_response
    raise error.APIError(
openai.error.APIError: Invalid response object from API: '{"detail":"Invalid request"}' (HTTP response code was 400)

```

**Comment by xusenlinzy** [comment]
刚刚修复了这个bug，请拉取最新的代码试试
