### ISSUE TITLE
利用微调后的Qwen+Lora模型运行时候报错

### ISSUE THREAD

**Issue by lucheng07082221** [xusenlinzy/api-for-open-llm#121]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

模型推理和部署 | Model inference and deployment

### 操作系统 | Operating system

None

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
# Paste the runtime code here (delete the code block if you don't have it)
```

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

利用微调后的Qwen+Lora模型运行时候报错
python3 api/app.py --port 80 --allow-credentials --model_name qwen --model_path ../models/Qwen-7B-Chat/ --device cuda --embedding_name ../models/m3e-base/ --gpus 4,5,6,7 --num_gpus 4 --adapter_model_path ../models/checkpoint-1000/ --prompt_name chatml

2023-09-14 16:40:46.192 | INFO     | api.router:main:492 - args: Namespace(adapter_model_path='../models/checkpoint-1000/', allow_credentials=True, allowed_headers=['*'], allowed_methods=['*'], allowed_origins=['*'], context_len=None, device='cuda', embedding_name='../models/m3e-base/', gpus='4,5,6,7', host='0.0.0.0', load_in_4bit=False, load_in_8bit=False, model_name='qwen', model_path='../models/Qwen-7B-Chat/', num_gpus=4, patch_type=None, port=80, prompt_name='chatml', quantize=16, stream_interval=2, training_length=4096, use_ptuning_v2=False, window_size=512)
The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Try importing flash-attention for faster inference...
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:12<00:00,  1.57s/it]
2023-09-14 16:41:02.383 | INFO     | api.model_adapter:load_adapter_model:142 - Vocab of the base model: 151936
2023-09-14 16:41:02.383 | INFO     | api.model_adapter:load_adapter_model:143 - Vocab of the tokenizer: 151851
tokenzier_vocab_size:  151851
model_vocab_size:  151936
Traceback (most recent call last):
  File "api/app.py", line 108, in <module>
    main(args)
  File "/workspace/api-for-open-llm/./api/router.py", line 495, in main
    model, tokenizer = load_model(
  File "/workspace/api-for-open-llm/./api/model_adapter.py", line 227, in load_model
    model, tokenizer = adapter.load_model(
  File "/workspace/api-for-open-llm/./api/model_adapter.py", line 114, in load_model
    model = self.load_adapter_model(model, tokenizer, adapter_model, is_chatglm, config_kwargs, **kwargs)
  File "/workspace/api-for-open-llm/./api/model_adapter.py", line 147, in load_adapter_model
    assert tokenzier_vocab_size > model_vocab_size
AssertionError

**Comment by xusenlinzy** [comment]
刚刚更新了代码，试试有没有问题~

**Comment by lucheng07082221** [comment]
可以了，多谢，您改了哪些东西呢？

**Comment by xusenlinzy** [comment]
将是否进行词表扩充设置为了参数传入方式，
修改内容这里可以看到 https://github.com/xusenlinzy/api-for-open-llm/commit/090059850d9e5fe127600f7f19105895b1f6d35d
