### ISSUE TITLE
transformer版本为4.34.0启动时，报'ChatGLMTokenizer' object has no attribute 'tokenizer'错误

### ISSUE THREAD

**Issue by linzhengtian** [xusenlinzy/api-for-open-llm#137]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

模型推理和部署 | Model inference and deployment

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

```
transformer版本为4.34.0时，api/apapter/model.py中tokenizer = self.tokenizer_class.from_pretrained(model_name_or_path, **tokenizer_kwargs)报错，当transformer版本小于4.34.0时，功能正常
```

### Dependencies

```
transformer==4.34.0
```

### 运行日志或截图 | Runtime logs or screenshots

```
Traceback (most recent call last):
  File "server.py", line 2, in <module>
    from api.models import EMBEDDED_MODEL, GENERATE_MDDEL, app, VLLM_ENGINE
  File "/home/api-for-open-llm-bak/api/models.py", line 135, in <module>
    GENERATE_MDDEL = create_generate_model() if (not config.USE_VLLM and config.ACTIVATE_INFERENCE) else None
  File "/home/api-for-open-llm-bak/api/models.py", line 43, in create_generate_model
    model, tokenizer = load_model(
  File "/home/api-for-open-llm-bak/api/apapter/model.py", line 242, in load_model
    model, tokenizer = adapter.load_model(
  File "/home/api-for-open-llm-bak/api/apapter/model.py", line 46, in load_model
    tokenizer = self.tokenizer_class.from_pretrained(model_name_or_path, **tokenizer_kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 738, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2045, in from_pretrained
    return cls._from_pretrained(
  File "/usr/local/python3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2256, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-6b/tokenization_chatglm.py", line 69, in __init__
    super().__init__(padding_side=padding_side, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 366, in __init__
    self._add_tokens(self.all_special_tokens_extended, special_tokens=True)
  File "/usr/local/python3/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 462, in _add_tokens
    current_vocab = self.get_vocab().copy()
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-6b/tokenization_chatglm.py", line 99, in get_vocab
    vocab = {self._convert_id_to_token(i): i for i in range(self.vocab_size)}
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-6b/tokenization_chatglm.py", line 95, in vocab_size
    return self.tokenizer.n_words
AttributeError: 'ChatGLMTokenizer' object has no attribute 'tokenizer'
```

**Comment by zy-myname** [comment]
我也遇到了……好无语

**Comment by xusenlinzy** [comment]
暂时先使用 transformer==4.33.2这个版本吧
