### ISSUE TITLE
Ubuntu服务器docker启动报错

### ISSUE THREAD

**Issue by Guwudao** [xusenlinzy/api-for-open-llm#19]
使用以下命令docker启动，启动以后会马上退出：
```
docker run -it -d --gpus all --ipc=host --net=host -p 80:80 --name=chatglm \
    --ulimit memlock=-1 --ulimit stack=67108864 \
    -v `pwd`:/workspace \
    llm-api:pytorch \
    python api/app.py \
    --port 80 \
    --allow-credentials \
    --model_name chatglm \
    --model_path THUDM/chatglm-6b \
    --embedding_name moka-ai/m3e-base
```

通过docker logs查看，报了以下error：
```
=============
== PyTorch ==
=============

NVIDIA Release 22.12 (build 49968248)
PyTorch Version 1.14.0a0+410ce96

Container image Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

Copyright (c) 2014-2022 Facebook Inc.
Copyright (c) 2011-2014 Idiap Research Institute (Ronan Collobert)
Copyright (c) 2012-2014 Deepmind Technologies    (Koray Kavukcuoglu)
Copyright (c) 2011-2012 NEC Laboratories America (Koray Kavukcuoglu)
Copyright (c) 2011-2013 NYU                      (Clement Farabet)
Copyright (c) 2006-2010 NEC Laboratories America (Ronan Collobert, Leon Bottou, Iain Melvin, Jason Weston)
Copyright (c) 2006      Idiap Research Institute (Samy Bengio)
Copyright (c) 2001-2004 Idiap Research Institute (Ronan Collobert, Samy Bengio, Johnny Mariethoz)
Copyright (c) 2015      Google Inc.
Copyright (c) 2015      Yangqing Jia
Copyright (c) 2013-2016 The Caffe contributors
All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

/opt/nvidia/nvidia_entrypoint.sh: line 49: exec: --: invalid option
exec: usage: exec [-cl] [-a name] [command [arguments ...]] [redirection ...]
```
谢谢~

**Comment by xusenlinzy** [comment]
我也不太清哪里有问题😅，您可以试一下改成下面的格式
```
docker run -it -d --gpus all --ipc=host --net=host -p 80:80 --name=chatglm \
    --ulimit memlock=-1 --ulimit stack=67108864 \
    -v `pwd`:/workspace \
    llm-api:pytorch \
    python api/app.py \
    --port=80 \
    --allow-credentials \
    --model_name=chatglm \
    --model_path=THUDM/chatglm-6b \
    --embedding_name=moka-ai/m3e-base
```

**Comment by xusenlinzy** [comment]
如果还是不行的话，可以分两步
1. 创建容器
```
docker run -it -d --gpus all --ipc=host --net=host -p 80:80 --name=chatglm \
    --ulimit memlock=-1 --ulimit stack=67108864 \
    -v `pwd`:/workspace \
    llm-api:pytorch
```
2. 进入容器启动模型
```
docker exec -it chatglm /bin/bash

python api/app.py \
    --port=80 \
    --allow-credentials \
    --model_name=chatglm \
    --model_path=THUDM/chatglm-6b \
    --embedding_name=moka-ai/m3e-base
```

**Comment by Guwudao** [comment]
按照这个步骤创建容器成功了：
```
docker run -it -d --gpus all --ipc=host --net=host -p 3010:3010 --name=chatglm --ulimit memlock=-1 --ulimit stack=67108864 -v `pwd`:/workspace llm-api:pytorch
```

但是进入容器启动模型时出现以下error：
```
root@iZrj9f884goskhjn2bmmc6Z:/workspace# python api/app.py --port=3010 --allow-credentials --model_name=chatglm --model_path=/ai-data/huggingface-models/THUDM/chatglm-6b --embedding_name=moka-ai/m3e-base
Traceback (most recent call last):
  File "api/app.py", line 19, in <module>
    from api.models import load_model
  File "/workspace/./api/models.py", line 7, in <module>
    from peft import PeftModel
  File "/usr/local/lib/python3.8/dist-packages/peft/__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "/usr/local/lib/python3.8/dist-packages/peft/mapping.py", line 20, in <module>
    from .peft_model import (
  File "/usr/local/lib/python3.8/dist-packages/peft/peft_model.py", line 26, in <module>
    from accelerate import dispatch_model, infer_auto_device_map
  File "/usr/local/lib/python3.8/dist-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 34, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/usr/local/lib/python3.8/dist-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/__init__.py", line 112, in <module>
    from .launch import (
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/launch.py", line 27, in <module>
    from ..utils.other import merge_dicts
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/other.py", line 24, in <module>
    from .transformer_engine import convert_model
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/transformer_engine.py", line 21, in <module>
    import transformer_engine.pytorch as te
  File "/usr/local/lib/python3.8/dist-packages/transformer_engine/__init__.py", line 7, in <module>
    from . import pytorch
  File "/usr/local/lib/python3.8/dist-packages/transformer_engine/pytorch/__init__.py", line 6, in <module>
    from .module import LayerNormLinear
  File "/usr/local/lib/python3.8/dist-packages/transformer_engine/pytorch/module.py", line 17, in <module>
    from .fp8 import (
  File "/usr/local/lib/python3.8/dist-packages/transformer_engine/pytorch/fp8.py", line 12, in <module>
    from transformer_engine.common.recipe import DelayedScaling, Format
  File "/usr/local/lib/python3.8/dist-packages/transformer_engine/common/recipe.py", line 53, in <module>
    class DelayedScaling:
  File "pydantic/dataclasses.py", line 224, in pydantic.dataclasses.dataclass.wrap
    #
  File "pydantic/dataclasses.py", line 336, in pydantic.dataclasses._add_pydantic_validation_attributes
    if default is not MISSING and default_factory is not MISSING:
  File "pydantic/dataclasses.py", line 391, in pydantic.dataclasses.create_pydantic_model_from_dataclass
    # Compute the text of the entire function.
  File "pydantic/main.py", line 1026, in pydantic.main.create_model
  File "pydantic/main.py", line 198, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 663, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 808, in pydantic.fields.ModelField._create_sub_type
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/usr/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```

另外想请教下 `--embedding_name` 这个参数的值是从哪里来的呢？
谢谢！

**Comment by xusenlinzy** [comment]
`--embedding_name moka-ai/m3e-base`  是指使用 `huggingface`上的  `moka-ai/m3e-base` 模型作为文本嵌入模型

**Comment by xusenlinzy** [comment]
出现的问题可以参考一下：https://github.com/xusenlinzy/api-for-open-llm/issues/8#issuecomment-1592632848

**Comment by Guwudao** [comment]
#8 解决了root validator的问题，不过遇到了 #9  的问题。
所以按照我的模型是存放在`/ai-data/huggingface-models/THUDM/chatglm-6b`

我是应该增加一个挂载目录对吗
```
docker run -it -d --gpus all --ipc=host --net=host -p 80:80 --name=chatglm \
    --ulimit memlock=-1 --ulimit stack=67108864 \
    -v `pwd`:/workspace \
    **-v /ai-data/huggingface-models/THUDM:/workspace \**
    llm-api:pytorch
```

**Comment by xusenlinzy** [comment]
是的

**Comment by Guwudao** [comment]
你好，我尝试修改挂载目录并启动成功了，但是尝试把Dify对接过去的时候遇到问题：

1. 首先之前基于 #8 升级 pydantic的遗留问题
`pip install --upgrade pydantic`
```
Requirement already satisfied: pydantic in /usr/local/lib/python3.8/dist-packages (1.10.2)
Collecting pydantic
  Downloading pydantic-2.0.2-py3-none-any.whl (359 kB)
     |████████████████████████████████| 359 kB 18.1 MB/s 
Collecting annotated-types>=0.4.0
  Downloading annotated_types-0.5.0-py3-none-any.whl (11 kB)
Collecting pydantic-core==2.1.2
  Downloading pydantic_core-2.1.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.8 MB)
     |████████████████████████████████| 1.8 MB 68.2 MB/s 
Requirement already satisfied: typing-extensions>=4.6.1 in /usr/local/lib/python3.8/dist-packages (from pydantic) (4.7.1)
Installing collected packages: pydantic-core, annotated-types, pydantic
  Attempting uninstall: pydantic
    Found existing installation: pydantic 1.10.2
    Uninstalling pydantic-1.10.2:
      Successfully uninstalled pydantic-1.10.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
thinc 8.1.5 requires pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4, but you have pydantic 2.0.2 which is incompatible.
spacy 3.4.4 requires pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4, but you have pydantic 2.0.2 which is incompatible.
langchainplus-sdk 0.0.20 requires pydantic<2,>=1, but you have pydantic 2.0.2 which is incompatible.
langchain 0.0.230 requires pydantic<2,>=1, but you have pydantic 2.0.2 which is incompatible.
confection 0.0.3 requires pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4, but you have pydantic 2.0.2 which is incompatible.
Successfully installed annotated-types-0.5.0 pydantic-2.0.2 pydantic-core-2.1.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 21.2.4; however, version 23.1.2 is available.
You should consider upgrading via the '/usr/bin/python -m pip install --upgrade pip' command.
```

虽然有error但是pydantic也升级到了2.0.2，并且启动成功了：
`python api/app.py --port=3010 --allow-credentials --model_name=chatglm --model_path=models/chatglm-6b --embedding_name=models/m3e-base`

2. 通过OpenAI chat completion的方法调用成功

3. 通过以下方式修改了Dify docker compose以后调用
```
# 在docker-compose.yml中的api和worker服务中添加以下环境变量
OPENAI_API_BASE: http://192.168.0.xx:80/v1
DISABLE_PROVIDER_CONFIG_VALIDATION: 'true'
```
会出现以下error：
```
api/app.py:152: PydanticDeprecatedSince20: The `json` method is deprecated; use `model_dump_json` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.0.2/migration/
  yield f"data: {chunk.json(exclude_unset=True, ensure_ascii=False)}\n\n"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/responses.py", line 277, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/usr/local/lib/python3.8/dist-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/usr/local/lib/python3.8/dist-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "api/app.py", line 152, in chat_completion_stream_generator
    yield f"data: {chunk.json(exclude_unset=True, ensure_ascii=False)}\n\n"
  File "/usr/local/lib/python3.8/dist-packages/typing_extensions.py", line 2562, in wrapper
    return __arg(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pydantic/main.py", line 926, in json
    raise TypeError('`dumps_kwargs` keyword arguments are no longer supported.')
TypeError: `dumps_kwargs` keyword arguments are no longer supported.
```

看起来是pydantic在2.0里`json`过期改成了`model_dump_json`

综上所述目前主要问题在于如果继续使用pydantic 1.10.2会遇到 #8 的问题，
但是升级到了2.0.2接入Dify也会有问题，不知道有没有什么解决方案呢

**Comment by xusenlinzy** [comment]
您好，可以试一下 `typing_extensions==4.4.0`，`pydantic==1.10.2`这个组合看看有没有问题

**Comment by Guwudao** [comment]
确实会有问题：
```
Traceback (most recent call last):
  File "api/app.py", line 11, in <module>
    from fastapi import FastAPI
  File "/usr/local/lib/python3.8/dist-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 16, in <module>
    from fastapi import routing
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 22, in <module>
    from fastapi import params
  File "/usr/local/lib/python3.8/dist-packages/fastapi/params.py", line 6, in <module>
    from typing_extensions import Annotated, deprecated
ImportError: cannot import name 'deprecated' from 'typing_extensions' (/usr/local/lib/python3.8/dist-packages/typing_extensions.py)
```

**Comment by xusenlinzy** [comment]
您这边显示的应该是chat completion的流式接口有问题

**Comment by xusenlinzy** [comment]
要不再试试 `pip install pydantic==1.10.8`

**Comment by Guwudao** [comment]
你好，我这边解决了，我看回 #8 里面的评论
`typing_extensions==4.4.0，pydantic==1.10.2，fastapi==0.95.1`
把fastapi的版本指定到0.95.1就可以了
