### ISSUE TITLE
加载Baichuan2-13B时出现TypeError: unsupported operand type(s) for |=: 'dict' and 'dict'

### ISSUE THREAD

**Issue by Zscozer** [xusenlinzy/api-for-open-llm#202]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

其他问题 | Other issues

### 操作系统 | Operating system

Linux

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

Traceback (most recent call last):
  File "server.py", line 2, in <module>
    from api.models import app, EMBEDDED_MODEL, GENERATE_ENGINE
  File "/usr/local/xx/xxx/code/rag-chatbot-zhg/api-for-open-llm-master/api/models.py", line 157, in <module>
    GENERATE_ENGINE = create_generate_model()
  File "/usr/local/xx/xxx/code/rag-chatbot-zhg/api-for-open-llm-master/api/models.py", line 49, in create_generate_model
    model, tokenizer = load_model(
  File "/usr/local/xx/xxx/code/rag-chatbot-zhg/api-for-open-llm-master/api/adapter/model.py", line 316, in load_model
    model, tokenizer = adapter.load_model(
  File "/usr/local/xx/xxx/code/rag-chatbot-zhg/api-for-open-llm-master/api/adapter/model.py", line 64, in load_model
    tokenizer_kwargs |= self.tokenizer_kwargs
TypeError: unsupported operand type(s) for |=: 'dict' and 'dict'

**Comment by xusenlinzy** [comment]
python版本的问题，已经修复了，拉一下最新代码试试
