### ISSUE TITLE
请问如何支持Qwen1.8B的模型？

### ISSUE THREAD

**Issue by lucheng07082221** [xusenlinzy/api-for-open-llm#216]
### 实现PR | Implementation PR

请问如何支持Qwen1.8B的模型？

### 相关Issues | Reference Issues

请问如何支持Qwen1.8B的模型？

### 摘要 | Summary

请问如何支持Qwen1.8B的模型？

### 基本示例 | Basic Example

请问如何支持Qwen1.8B的模型？

### 缺陷 | Drawbacks

请问如何支持Qwen1.8B的模型？

**Comment by xusenlinzy** [comment]
MODEL_NAME=qwen

**Comment by lucheng07082221** [comment]
抱歉，运行出错了

lc@lc-ConceptD-CT500-51A:~/api-for-open-llm$ python3 server.py 
2023-12-27 14:28:03.577 | DEBUG    | api.config:<module>:130 - Config: {'HOST': '0.0.0.0', 'PORT': 8000, 'MODEL_NAME': 'qwen', 'MODEL_PATH': '/media/lc/lc/Qwen-1.8B-Chat', 'ADAPTER_MODEL_PATH': None, 'RESIZE_EMBEDDINGS': False, 'DEVICE': 'cuda', 'DEVICE_MAP': None, 'GPUS': '', 'NUM_GPUs': 1, 'ONLY_EMBEDDING': False, 'EMBEDDING_NAME': '/media/lc/lc/word_embedding_model/m3e-base', 'EMBEDDING_SIZE': None, 'EMBEDDING_DEVICE': 'cuda', 'QUANTIZE': 16, 'LOAD_IN_8BIT': False, 'LOAD_IN_4BIT': True, 'USING_PTUNING_V2': False, 'CONTEXT_LEN': None, 'STREAM_INTERVERL': 2, 'PROMPT_NAME': None, 'PATCH_TYPE': None, 'ALPHA': 'auto', 'API_PREFIX': '/v1', 'USE_VLLM': False, 'TRUST_REMOTE_CODE': False, 'TOKENIZE_MODE': 'auto', 'TENSOR_PARALLEL_SIZE': 1, 'DTYPE': 'half', 'GPU_MEMORY_UTILIZATION': 0.9, 'MAX_NUM_BATCHED_TOKENS': None, 'MAX_NUM_SEQS': 256, 'QUANTIZATION_METHOD': None, 'USE_STREAMER_V2': False, 'API_KEYS': None, 'ACTIVATE_INFERENCE': True}
No sentence-transformers model found with name /media/lc/lc/word_embedding_model/m3e-base. Creating a new one with MEAN pooling.
Traceback (most recent call last):
  File "/home/lc/api-for-open-llm/server.py", line 2, in <module>
    from api.models import EMBEDDED_MODEL, GENERATE_MDDEL, app, VLLM_ENGINE
  File "/home/lc/api-for-open-llm/api/models.py", line 133, in <module>
    GENERATE_MDDEL = create_generate_model() if (not config.USE_VLLM and config.ACTIVATE_INFERENCE) else None
  File "/home/lc/api-for-open-llm/api/models.py", line 43, in create_generate_model
    model, tokenizer = load_model(
  File "/home/lc/api-for-open-llm/api/apapter/model.py", line 242, in load_model
    model, tokenizer = adapter.load_model(
  File "/home/lc/api-for-open-llm/api/apapter/model.py", line 46, in load_model
    tokenizer = self.tokenizer_class.from_pretrained(model_name_or_path, **tokenizer_kwargs)
  File "/usr/local/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 734, in from_pretrained
    tokenizer_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 497, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "/usr/local/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 199, in get_class_in_module
    module = importlib.import_module(module_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'transformers_modules.Qwen-1'


这是我的参数设置：
PORT=8000

# model related
MODEL_NAME=qwen
MODEL_PATH=/media/lc/lc/Qwen-1.8B-Chat
EMBEDDING_NAME=/media/lc/lc/word_embedding_model/m3e-base
ADAPTER_MODEL_PATH=
QUANTIZE=16
CONTEXT_LEN=
LOAD_IN_8BIT=false
LOAD_IN_4BIT=true
USING_PTUNING_V2=false
STREAM_INTERVERL=2
PROMPT_NAME=

# device related
DEVICE=cuda
DEVICE_MAP=
GPUS=
NUM_GPUs=1
DTYPE=half

# patch related
PATCH_TYPE=

# api related
API_PREFIX=/v1

USE_STREAMER_V2=false

**Comment by xusenlinzy** [comment]
看样子应该是transformers的版本问题，你可以更新一下项目代码，按照最新的requirements.txt安装依赖

**Comment by lucheng07082221** [comment]
更新了最新的代码，也按照pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.tx 要求重新安装依赖
然后还是报错：
Traceback (most recent call last):
  File "/home/lc/api-for-open-llm/server.py", line 2, in <module>
    from api.models import app, EMBEDDED_MODEL, GENERATE_ENGINE
  File "/home/lc/api-for-open-llm/api/models.py", line 161, in <module>
    GENERATE_ENGINE = create_generate_model()
  File "/home/lc/api-for-open-llm/api/models.py", line 53, in create_generate_model
    model, tokenizer = load_model(
  File "/home/lc/api-for-open-llm/api/adapter/model.py", line 316, in load_model
    model, tokenizer = adapter.load_model(
  File "/home/lc/api-for-open-llm/api/adapter/model.py", line 77, in load_model
    tokenizer = self.tokenizer_class.from_pretrained(
  File "/usr/local/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 770, in from_pretrained
    tokenizer_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 500, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "/usr/local/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 200, in get_class_in_module
    module = importlib.import_module(module_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'transformers_modules.Qwen-1'

**Comment by lucheng07082221** [comment]
重新下载模型修复了，谢谢
