### ISSUE TITLE
使用 llama-cpp 部署模型推理时报错

### ISSUE THREAD

**Issue by Tendo33** [xusenlinzy/api-for-open-llm#217]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

模型推理和部署 | Model inference and deployment

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

我使用llama-cpp的Docker 把模型部署上去之后，在本地尝试使用脚本推理

推理脚本：
```
def response_create(role_content, query_content, model_ip, temperature=0.9, frequency_penalty=0.0, presence_penalty=0.0):

    client = OpenAI(
        api_key="xxx",
        base_url=model_ip
    )
    # 使用OpenAI ChatCompletion API生成聊天响应
    response = client.chat.completions.create(
        model='Qwen-7B',  
        messages=[
            {"role": "system", "content": role_content},  
            {"role": "user", "content": query_content},  
        ],
        max_tokens=32000,  
        # top_p=0.95, 
        # memory_k=5, 
        # chunk_size=200, 
        # chunk_overlap=0,  
        temperature=temperature,  
        frequency_penalty=frequency_penalty, 
        presence_penalty=presence_penalty,  
    )

    output = response.choices[0].message.content.strip()
    return output
```

### Dependencies

```
peft                          0.6.2
torch                         2.1.0
transformers                  4.31.0
transformers-stream-generator 0.0.4
pydantic                      2.5.2
openai                        1.1.0
```

### 运行日志或截图 | Runtime logs or screenshots

```
INFO:     10.0.34.61:38362 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 116, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 746, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 75, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 70, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/workspace/api/llama_cpp_routes/chat.py", line 50, in create_chat_completion
    iterator_or_completion = await run_in_threadpool(
  File "/usr/local/lib/python3.10/dist-packages/starlette/concurrency.py", line 35, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/workspace/api/core/llama_cpp_engine.py", line 161, in create_chat_completion
    else self._create_chat_completion(prompt, **kwargs)
  File "/workspace/api/core/llama_cpp_engine.py", line 96, in _create_chat_completion
    choice = Choice(
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Choice
logprobs
  Field required [type=missing, input_value={'index': 0, 'message': C...'finish_reason': 'stop'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
```

**Comment by xusenlinzy** [comment]
试试安装pydantic==1.10.13呢

**Comment by Tendo33** [comment]
> 试试安装pydantic==1.10.13或者拉一下最新的代码安装openai>=1.6.1
版本更新为这样还是一样的错误：
```
pydantic                      1.10.13
openai                        1.1.0
```
安装了最新的Openai 之后也不可以
但是开启`stream=True`之后可以使用

**Comment by tongcu** [comment]
请问有没有针对llama-cpp 打包好的 images？遇到类似的问题，部署其他模型没有问题，但是llama-cpp（用对应的dockfile）也是报错

**Comment by Tendo33** [comment]
> 请问有没有针对llama-cpp 打包好的 images？遇到类似的问题，部署其他模型没有问题，但是llama-cpp（用对应的dockfile）也是报错

我就是针对 llama-cpp 打包的image，然后启的容器。但是普通的启动方式（就是最基本的DockerFile）推理是没有问题的
