### ISSUE TITLE
Traceback (most recent call last):   File "/Users/yaoxingzhi/Desktop/api-for-open-llm-master/api/server.py", line 1, in <module>     from api.config import SETTINGS ModuleNotFoundError: No module named 'api'

### ISSUE THREAD

**Issue by 779257747** [xusenlinzy/api-for-open-llm#254]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

启动命令 | Startup command

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

```
(openllm) yaoxingzhi@yaoxingzhideMacBook-Pro api % export PYTHONPATH=.                 
(openllm) yaoxingzhi@yaoxingzhideMacBook-Pro api % python server.py 

```

### Dependencies

```
python=3.10
```

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```

**Comment by 779257747** [comment]
Traceback (most recent call last):
  File "/Users/yaoxingzhi/Desktop/api-for-open-llm-master/api/server.py", line 1, in <module>
    from api.config import SETTINGS
ModuleNotFoundError: No module named 'api'
在issue里的方法已经尝试过了 都不奏效 ， 是不是得手动把所有的api.删掉。。
