### ISSUE TITLE
接口请求报错：TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]

### ISSUE THREAD

**Issue by syusama** [xusenlinzy/api-for-open-llm#282]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

模型推理和部署 | Model inference and deployment

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

通过docker命令启动，
```
docker compose -f .\docker-compose.vllm.l-qwen.yml up -d
```
服务成功启动，但是调用接口后台就报错
```
TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]
```

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
2024-06-07 15:44:54 api-for-open-llm-vllmapiserver-1  | INFO:     Started server process [1]
2024-06-07 15:44:54 api-for-open-llm-vllmapiserver-1  | INFO:     Waiting for application startup.
2024-06-07 15:44:54 api-for-open-llm-vllmapiserver-1  | INFO:     Application startup complete.
2024-06-07 15:44:54 api-for-open-llm-vllmapiserver-1  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2024-06-07 15:45:25 api-for-open-llm-vllmapiserver-1  | 2024-06-07 07:45:25.495 | DEBUG    | api.vllm_routes.chat:create_chat_completion:65 - ==== request ====
2024-06-07 15:45:25 api-for-open-llm-vllmapiserver-1  | {'model': 'Qwen1.5-14B-Chat', 'frequency_penalty': 0.0, 'function_call': None, 'functions': None, 'logit_bias': None, 'logprobs': False, 'max_tokens': 8000, 'n': 1, 'presence_penalty': 0.0, 'response_format': None, 'seed': None, 'stop': ['<|endoftext|>', '<|im_end|>'], 'temperature': 0.01, 'tool_choice': None, 'tools': None, 'top_logprobs': None, 'top_p': 1.0, 'user': None, 'stream': True, 'repetition_penalty': 1.03, 'typical_p': None, 'watermark': False, 'best_of': 1, 'ignore_eos': False, 'use_beam_search': False, 'stop_token_ids': [], 'skip_special_tokens': True, 'spaces_between_special_tokens': True, 'min_p': 0.0, 'include_stop_str_in_output': False, 'length_penalty': 1.0, 'guided_json': None, 'guided_regex': None, 'guided_choice': None, 'guided_grammar': None, 'guided_decoding_backend': None, 'prompt_or_messages': [{'content': '你好', 'role': 'user'}], 'echo': False}
2024-06-07 15:45:25 api-for-open-llm-vllmapiserver-1  | INFO:     172.22.0.1:50584 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  | ERROR:    Exception in ASGI application
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  | Traceback (most recent call last):
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   File "/usr/local/lib/python3.10/dist-packages/sse_starlette/sse.py", line 282, in __call__
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     await wrap(partial(self.listen_for_disconnect, receive))
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   File "/usr/local/lib/python3.10/dist-packages/sse_starlette/sse.py", line 271, in wrap
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     await func()
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   File "/usr/local/lib/python3.10/dist-packages/sse_starlette/sse.py", line 221, in listen_for_disconnect
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     message = await receive()
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 553, in receive
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     await self.message_event.wait()
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   File "/usr/lib/python3.10/asyncio/locks.py", line 214, in wait
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     await fut
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  | asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f569407e290
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  | 
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  | During handling of the above exception, another exception occurred:
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  | 
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   + Exception Group Traceback (most recent call last):
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |     result = await app(  # type: ignore[func-returns-value]
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |     return await self.app(scope, receive, send)
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |   File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1054, in __call__
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |     await super().__call__(scope, receive, send)
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 123, in __call__
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |     await self.middleware_stack(scope, receive, send)
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 186, in __call__
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |     raise exc
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 164, in __call__
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |     await self.app(scope, receive, _send)
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 85, in __call__
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |     await self.app(scope, receive, send)
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |     raise exc
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |     await app(scope, receive, sender)
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 756, in __call__
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |     await self.middleware_stack(scope, receive, send)
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 776, in app
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |     await route.handle(scope, receive, send)
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 297, in handle
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |     await self.app(scope, receive, send)
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 77, in app
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |     raise exc
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |     await app(scope, receive, sender)
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 75, in app
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |     await response(scope, receive, send)
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |   File "/usr/local/lib/python3.10/dist-packages/sse_starlette/sse.py", line 268, in __call__
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |     async with anyio.create_task_group() as task_group:
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |   File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 680, in __aexit__
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   |     raise BaseExceptionGroup(
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |   +-+---------------- 1 ----------------
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     | Traceback (most recent call last):
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     |   File "/workspace/api/utils/request.py", line 159, in get_event_publisher
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     |     async for chunk in iterator:
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     |   File "/workspace/api/vllm_routes/chat.py", line 259, in create_chat_completion_stream
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     |     async for res in generator:
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 666, in generate
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     |     raise e
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 650, in generate
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     |     stream = await self.add_request(
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 556, in add_request
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     |     prompt_token_ids = await self.engine.encode_request_async(
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 244, in encode_request_async
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     |     prompt_token_ids = await self.tokenizer.encode_async(
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     |   File "/usr/local/lib/python3.10/dist-packages/vllm/transformers_utils/tokenizer_group/tokenizer_group.py", line 50, in encode_async
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     |     return tokenizer.encode(prompt)
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     |   File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 2654, in encode
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     |     encoded_inputs = self.encode_plus(
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     |   File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 3062, in encode_plus
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     |     return self._encode_plus(
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     |   File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 583, in _encode_plus
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     |     batched_output = self._batch_encode_plus(
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     |   File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 511, in _batch_encode_plus
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     |     encodings = self._tokenizer.encode_batch(
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     | TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]
2024-06-07 15:45:26 api-for-open-llm-vllmapiserver-1  |     +------------------------------------
```
![1717748868181](https://github.com/xusenlinzy/api-for-open-llm/assets/16223129/b5545601-377c-45ac-9711-afaf6b933472)

**Comment by xusenlinzy** [comment]
能看一下docker-compose里面的配置吗

**Comment by syusama** [comment]
> 能看一下docker-compose里面的配置吗

`version: '3.10'

services:
  apiserver:
    image: llm-api:pytorch
    command: python api/server.py
    ulimits:
      stack: 67108864
      memlock: -1
    environment:
      - PORT=8000
      - MODEL_NAME=qwen2
      - MODEL_PATH=checkpoints/Liberated-Qwen1.5-14B
      - EMBEDDING_NAME=checkpoints/bce-embedding-base_v1
      - DEVICE_MAP=auto
      - TENSOR_PARALLEL_SIZE=2
      - TRUST_REMOTE_CODE=true
    volumes:
      - D:\projects\api-for-open-llm\api-for-open-llm:/workspace
      # model path need to be specified if not in pwd
      - D:\projects\Qwen\models:/workspace/checkpoints
    env_file:
      - .env.l-qwen
    ports:
      - "8053:8000"
    restart: always
    networks:
      - apinet
    shm_size: 200g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0','1']  # 指定gpu
              capabilities: [gpu]

networks:
  apinet:
    driver: bridge
    name: apinet`

**Comment by syusama** [comment]
> 能看一下docker-compose里面的配置吗

`version: '3.10'

services:
  vllmapiserver:
    image: llm-api:vllm
    command: python api/server.py
    ulimits:
      stack: 67108864
      memlock: -1
    environment:
      - PORT=8000
      - MODEL_NAME=qwen2
      - MODEL_PATH=checkpoints/Qwen1.5-14B-Chat
      - EMBEDDING_NAME=checkpoints/bce-embedding-base_v1
      - TENSOR_PARALLEL_SIZE=2
      - TRUST_REMOTE_CODE=true
    volumes:
      - D:\projects\api-for-open-llm\api-for-open-llm:/workspace
      # model path need to be specified if not in pwd
      - D:\projects\Qwen\models:/workspace/checkpoints
    env_file:
      - .env.l-qwen.vllm
    ports:
      - "8053:8000"
    restart: always
    networks:
      - vllmapinet
    shm_size: 200g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0','1']  # 指定gpu
              capabilities: [gpu]

networks:
  vllmapinet:
    driver: bridge
    name: vllmapinet`

**Comment by xusenlinzy** [comment]
试试环境变量指定PROMPT_NAME=qwen2

**Comment by syusama** [comment]
> 试试环境变量指定PROMPT_NAME=qwen2

我在docker-compose里和.env文件里都加了PROMPT_NAME=qwen2，但是还是报这个错

**Comment by xusenlinzy** [comment]
代码是最新的吗

**Comment by syusama** [comment]
> 代码是最新的吗

是最新的，我更新过代码，然后重新用docker打包的镜像

**Comment by xusenlinzy** [comment]
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/111472355/22a3fe42-4e07-468e-b10f-28017f6f82c8)
我这个配置启动是没问题

**Comment by xusenlinzy** [comment]
貌似是vllm的版本问题导致多卡可能出现问题，我已经更新了代码，你可以试试拉一下代码看看行不行

**Comment by syusama** [comment]
> 貌似是vllm的版本问题导致多卡可能出现问题，我已经更新了代码，你可以试试拉一下代码看看行不行

感谢大佬！重新拉了代码并更新了镜像，问题已解决！
但是又出现一个新的问题，就是llm接口没问题，但是embedding接口始终404，我找了类似的问题issue可还是没能解决我的问题，我重新提一个issue https://github.com/xusenlinzy/api-for-open-llm/issues/283，这个我就先关闭了哈
再次感谢！！
