### ISSUE TITLE
想要加载文件至向量库，报错"zipfile.BadZipFile: File is not a zip file"

### ISSUE THREAD

**Issue by TheBobbyliu** [xusenlinzy/api-for-open-llm#29]
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/34710660/04fa3614-2e4a-4f19-bab9-3b50722c0dbc)
2023-07-20 17:47:04.335 | DEBUG    | tools.doc_qa:get_documents:82 - Loading documents...
2023-07-20 17:47:04.335 | INFO     | tools.doc_qa:_get_documents:30 - Loading file: doc_store/chatgpt.txt
2023-07-20 17:47:04.337 | ERROR    | tools.doc_qa:_get_documents:74 - Error loading file: doc_store/chatgpt.txt
Traceback (most recent call last):
  File "/storage/workplace/liuyw/project/api-for-open-llm-master/applications/tools/doc_qa.py", line 71, in _get_documents
    return loader.load_and_split(text_splitter=text_splitter)
  File "/home/user/Downloads/enter/envs/openllm_test/lib/python3.9/site-packages/langchain/document_loaders/base.py", line 43, in load_and_split
    docs = self.load()
  File "/home/user/Downloads/enter/envs/openllm_test/lib/python3.9/site-packages/langchain/document_loaders/unstructured.py", line 86, in load
    elements = self._get_elements()
  File "/home/user/Downloads/enter/envs/openllm_test/lib/python3.9/site-packages/langchain/document_loaders/unstructured.py", line 167, in _get_elements
    from unstructured.partition.auto import partition
  File "/home/user/Downloads/enter/envs/openllm_test/lib/python3.9/site-packages/unstructured/partition/auto.py", line 16, in <module>
    from unstructured.partition.doc import partition_doc
  File "/home/user/Downloads/enter/envs/openllm_test/lib/python3.9/site-packages/unstructured/partition/doc.py", line 8, in <module>
    from unstructured.partition.docx import partition_docx
  File "/home/user/Downloads/enter/envs/openllm_test/lib/python3.9/site-packages/unstructured/partition/docx.py", line 33, in <module>
    from unstructured.partition.text_type import (
  File "/home/user/Downloads/enter/envs/openllm_test/lib/python3.9/site-packages/unstructured/partition/text_type.py", line 21, in <module>
    from unstructured.nlp.tokenize import pos_tag, sent_tokenize, word_tokenize
  File "/home/user/Downloads/enter/envs/openllm_test/lib/python3.9/site-packages/unstructured/nlp/tokenize.py", line 32, in <module>
    _download_nltk_package_if_not_present(package_name, package_category)
  File "/home/user/Downloads/enter/envs/openllm_test/lib/python3.9/site-packages/unstructured/nlp/tokenize.py", line 21, in _download_nltk_package_if_not_present
    nltk.find(f"{package_category}/{package_name}")
  File "/home/user/Downloads/enter/envs/openllm_test/lib/python3.9/site-packages/nltk/data.py", line 555, in find
    return find(modified_name, paths)
  File "/home/user/Downloads/enter/envs/openllm_test/lib/python3.9/site-packages/nltk/data.py", line 542, in find
    return ZipFilePathPointer(p, zipentry)
  File "/home/user/Downloads/enter/envs/openllm_test/lib/python3.9/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/home/user/Downloads/enter/envs/openllm_test/lib/python3.9/site-packages/nltk/data.py", line 394, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "/home/user/Downloads/enter/envs/openllm_test/lib/python3.9/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/home/user/Downloads/enter/envs/openllm_test/lib/python3.9/site-packages/nltk/data.py", line 935, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "/home/user/Downloads/enter/envs/openllm_test/lib/python3.9/zipfile.py", line 1266, in __init__
    self._RealGetContents()
  File "/home/user/Downloads/enter/envs/openllm_test/lib/python3.9/zipfile.py", line 1333, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by xusenlinzy** [comment]
您好，请拉取最新的代码测试一下哈~

**Comment by TheBobbyliu** [comment]
拉了最新的代码，发现还是会报相同的错误，这个是我的环境：
`accelerate==0.21.0
aiofiles==23.1.0
aiohttp==3.8.5
aiosignal==1.3.1
altair==5.0.1
anyio==3.7.1
appdirs==1.4.4
asgiref==3.7.2
async-timeout==4.0.2
attrs==23.1.0
backoff==2.2.1
bentoml==1.0.24
bitsandbytes==0.39.1
bitsandbytes-cuda117==0.26.0.post2
build==0.10.0
cattrs==23.1.2
certifi==2023.5.7
cffi==1.15.1
chardet==5.1.0
charset-normalizer==3.2.0
circus==0.18.0
click==8.1.6
click-option-group==0.5.6
cloudpickle==2.2.1
cmake==3.27.0
coloredlogs==15.0.1
contextlib2==21.6.0
contourpy==1.1.0
cpm-kernels==1.0.11
cryptography==41.0.2
cuda-python==12.2.0
cycler==0.11.0
Cython==3.0.0
dataclasses-json==0.5.12
datasets==2.13.1
deepmerge==1.1.0
Deprecated==1.2.14
dill==0.3.6
et-xmlfile==1.1.0
exceptiongroup==1.1.2
faiss-cpu==1.7.4
faiss-gpu==1.7.2
fastapi==0.95.1
ffmpy==0.3.1
filelock==3.12.2
filetype==1.2.0
fonttools==4.41.0
frozenlist==1.4.0
fs==2.4.16
fsspec==2023.6.0
gradio==3.37.0
gradio_client==0.2.10
greenlet==2.0.2
grpcio==1.56.2
grpcio-health-checking==1.56.2
h11==0.14.0
httpcore==0.17.3
httpx==0.24.1
huggingface-hub==0.16.4
humanfriendly==10.0
idna==3.4
importlib-metadata==6.0.1
importlib-resources==6.0.0
inflection==0.5.1
Jinja2==3.1.2
joblib==1.3.1
jsonschema==4.18.4
jsonschema-specifications==2023.7.1
kiwisolver==1.4.4
langchain==0.0.237
langsmith==0.0.10
latex2mathml==3.76.0
linkify-it-py==2.0.2
lit==16.0.6
loguru==0.7.0
lxml==4.9.3
Markdown==3.4.3
markdown-it-py==2.2.0
MarkupSafe==2.1.3
marshmallow==3.19.0
matplotlib==3.7.2
mdit-py-plugins==0.3.3
mdtex2html==1.2.0
mdurl==0.1.2
mpmath==1.3.0
msg-parser==1.2.0
multidict==6.0.4
multiprocess==0.70.14
mypy-extensions==1.0.0
networkx==3.1
nltk==3.8.1
numexpr==2.8.4
numpy==1.25.1
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
olefile==0.46
openai==0.27.8
openapi-schema-pydantic==1.2.4
openllm==0.2.0
openpyxl==3.1.2
opentelemetry-api==1.18.0
opentelemetry-instrumentation==0.39b0
opentelemetry-instrumentation-aiohttp-client==0.39b0
opentelemetry-instrumentation-asgi==0.39b0
opentelemetry-instrumentation-grpc==0.39b0
opentelemetry-sdk==1.18.0
opentelemetry-semantic-conventions==0.39b0
opentelemetry-util-http==0.39b0
optimum==1.9.1
orjson==3.9.2
packaging==23.1
pandas==2.0.3
pathspec==0.11.1
pdf2image==1.16.3
pdfminer.six==20221105
pdfplumber==0.10.1
peft==0.4.0
Pillow==10.0.0
pip-requirements-parser==32.0.1
pip-tools==7.1.0
prometheus-client==0.17.1
protobuf==4.23.4
psutil==5.9.5
pyarrow==12.0.1
pycparser==2.21
pydantic==1.10.11
pydub==0.25.1
Pygments==2.15.1
pynvml==11.5.0
pypandoc==1.11
pyparsing==3.0.9
pypdfium2==4.18.0
pyproject_hooks==1.0.0
python-dateutil==2.8.2
python-docx==0.8.11
python-json-logger==2.0.7
python-magic==0.4.27
python-multipart==0.0.6
python-pptx==0.6.21
pytz==2023.3
PyYAML==6.0.1
pyzmq==25.1.0
referencing==0.30.0
regex==2023.6.3
requests==2.31.0
rich==13.4.2
rpds-py==0.9.2
safetensors==0.3.1
schema==0.7.5
scikit-learn==1.3.0
scipy==1.11.1
semantic-version==2.10.0
sentence-transformers==2.2.2
sentencepiece==0.1.99
simple-di==0.1.5
six==1.16.0
sniffio==1.3.0
SQLAlchemy==2.0.19
starlette==0.26.1
sympy==1.12
tabulate==0.9.0
tenacity==8.2.2
threadpoolctl==3.2.0
tiktoken==0.4.0
tokenizers==0.13.3
tomli==2.0.1
toolz==0.12.0
torch==2.0.1
torchvision==0.15.2
tornado==6.3.2
tqdm==4.65.0
transformers==4.31.0
transformers-stream-generator==0.0.4
triton==2.0.0
typing-inspect==0.9.0
typing_extensions==4.7.1
tzdata==2023.3
uc-micro-py==1.0.2
unstructured==0.8.1
urllib3==2.0.4
uvicorn==0.23.1
watchfiles==0.19.0
wcwidth==0.2.6
websockets==11.0.3
wrapt==1.15.0
xlrd==2.0.1
XlsxWriter==3.1.2
xxhash==3.2.0
yarl==1.9.2
zipp==3.16.2`
