### ISSUE TITLE
报错mixed dtype (CPU): expect input to have scalar type of BFloat16)","code":50001

### ISSUE THREAD

**Issue by DXQer** [xusenlinzy/api-for-open-llm#4]
本地启动，使用CPU模式运行时报错：

Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 331, in handle_error_response
    error_data = resp["error"]
KeyError: 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxx\Downloads\api-for-open-llm-master-adapt\api-for-open-llm-master\api\untitled0.py", line 16, in <module>
    completion = openai.ChatCompletion.create(
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 333, in handle_error_response
    raise error.APIError(
openai.error.APIError: Invalid response object from API: '{"object":"error","message":"**NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.**\\n\\n(mixed dtype (CPU): expect input to have scalar type of BFloat16)","code":50001}' (HTTP response code was 500)

**Comment by xusenlinzy** [comment]
应该是模型精度的问题，已经重新提交了代码，你可以看看最新的代码运行有没有问题
