### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by happyfire** [xusenlinzy/api-for-open-llm#58]
运行环境: win10 + WSL2(Ubuntu 22.04)
按照文档安装了新的虚拟环境并安装了依赖：

> 安装 pytorch 环境
conda create -n pytorch python=3.8
conda activate pytorch
conda install pytorch cudatoolkit -c pytorch
安装依赖包
pip install -r requirements.txt

运行命令行为：

> (pytorch) wmjy@BuildMachine:~/api-for-open-llm$ cat runBaichuan13b.sh
python3 api/app.py \
    --port 6666 \
    --allow-credentials \
    --model_name baichuan-13b-chat \
    --model_path /home/wmjy/llm/baichuan-inc/Baichuan-13B-Chat \
    --device cuda \
    --quantize 8(pytorch)

起始执行输出：

> (pytorch) wmjy@BuildMachine:~/api-for-open-llm$ sh runBaichuan13b.sh
/home/wmjy/miniconda3/envs/pytorch/lib/python3.8/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/wmjy/miniconda3/envs/pytorch/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
2023-08-11 19:00:05.787 | INFO     | api.router:main:492 - args: Namespace(adapter_model_path=None, allow_credentials=True, allowed_headers=['*'], allowed_methods=['*'], allowed_origins=['*'], context_len=None, device='cuda', embedding_name=None, gpus=None, host='0.0.0.0', load_in_4bit=False, load_in_8bit=False, model_name='baichuan-13b-chat', model_path='/home/wmjy/llm/baichuan-inc/Baichuan-13B-Chat', num_gpus=1, patch_type=None, port=6666, prompt_name=None, quantize=8, stream_interval=2, training_length=4096, use_ptuning_v2=False, window_size=512)
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 3/3 [00:14<00:00,  4.73s/it]
2023-08-11 19:02:40.242 | INFO     | api.model_adapter:load_model:119 - Quantizing model to 8 bit.

这儿有个警告“The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.”

然后客户端连接上去请求chat completion之后，显示报错：

> 2023-08-11 19:02:40.242 | INFO     | api.model_adapter:load_model:119 - Quantizing model to 8 bit.
Traceback (most recent call last):
  File "api/app.py", line 108, in <module>
    main(args)
  File "/home/wmjy/api-for-open-llm/./api/router.py", line 495, in main
    model, tokenizer = load_model(
  File "/home/wmjy/api-for-open-llm/./api/model_adapter.py", line 226, in load_model
    model, tokenizer = adapter.load_model(
  File "/home/wmjy/api-for-open-llm/./api/model_adapter.py", line 123, in load_model
    model.to(device)
  File "/home/wmjy/miniconda3/envs/pytorch/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1900, in to
    return super().to(*args, **kwargs)
  File "/home/wmjy/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/home/wmjy/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/wmjy/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/wmjy/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/wmjy/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/wmjy/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

全新创建的虚拟环境和安装的依赖，请问是什么原因呢？还需要安装什么，或者是否是WSL的问题

**Comment by xusenlinzy** [comment]
您好，我这边使用的是docker环境，不方便进行测试，docker环境中torch版本是1.14，您可以参考https://blog.csdn.net/m0_46948660/article/details/129205116?utm_medium=distribute.pc_relevant.none-task-blog-2~default~baidujs_baidulandingword~default-0-129205116-blog-125737765.235^v38^pc_relevant_anti_vip&spm=1001.2101.3001.4242.1&utm_relevant_index=3 ，看能不能解决

**Comment by happyfire** [comment]
多谢，我磁盘快满了，之前只剩40G，docker build之后就只剩17G了，然后把image删了怎么清理也就24G，现在不敢试docker了，等下周换个新硬盘再试试

**Comment by JinguangHe** [comment]
> 您好，我这边使用的是docker环境，不方便进行测试，docker环境中torch版本是1.14，您可以参考[https://blog.csdn.net/m0_46948660/article/details/129205116?utm_medium=distribute.pc_relevant.none-task-blog-2~default~baidujs_baidulandingword~default-0-129205116-blog-125737765.235^v38^pc_relevant_anti_vip&spm=1001.2101.3001.4242.1&utm_relevant_index=3](https://blog.csdn.net/m0_46948660/article/details/129205116?utm_medium=distribute.pc_relevant.none-task-blog-2~default~baidujs_baidulandingword~default-0-129205116-blog-125737765.235%5Ev38%5Epc_relevant_anti_vip&spm=1001.2101.3001.4242.1&utm_relevant_index=3) ，看能不能解决

官方已经没有1.14了，换成2.0了。https://pytorch.org/get-started/pytorch-2.0/
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/128205718/96c6cb42-baa1-46bd-8c0f-e88a59308c76)
