### ISSUE TITLE
ValueError: Out of range float values are not JSON compliant

### ISSUE THREAD

**Issue by 143heyan** [xusenlinzy/api-for-open-llm#89]
### 问题类型 | Type of problem

模型推理和部署 | Model inference and deployment

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem
```
from langchain.chat_models import ChatOpenAI

api_key = "EMPTY"
api_base = "http://0.0.0.0:8501/v1"

llm = ChatOpenAI(temperature=0, openai_api_base=api_base,openai_api_key=api_key)
llm.call_as_llm("你是谁")
```

qwen模型可以正常使用，用百川13b出现ValueError: Out of range float values are not JSON compliant错误，求助

### 运行日志或截图 | Runtime logs or screenshots
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 266, in app
    response = actual_response_class(content, **response_args)
  File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 196, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 55, in __init__
    self.body = self.render(content)
  File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 199, in render
    return json.dumps(
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Out of range float values are not JSON compliant
```

**Comment by xusenlinzy** [comment]
您好，我的测试结果是
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/111472355/2944e2ea-e4c9-4b5f-a578-2dcb60712bca)
好像没有这个错误

**Comment by 143heyan** [comment]
我是一个A40 80G，直接跑不起来baichuan13B，用了8bit量化，和这个有关系吗？
"""
'QUANTIZE': 16,
'LOAD_IN_8BIT': 'True',
"""

**Comment by xusenlinzy** [comment]
没有，我上面的结果也是8bit量化的，你拉取最新的代码试试，我删了一些无关的代码

**Comment by 143heyan** [comment]
我试试最新的代码，谢谢，前面说错了，A100 40G
