### ISSUE TITLE
docker启动报错

### ISSUE THREAD

**Issue by jinghai** [xusenlinzy/api-for-open-llm#9]
启动命令：
```
docker run -it -d --gpus 2 --ipc=host --net=bridge -p 6006:6006 --name=chatglm \
    --ulimit memlock=-1 --ulimit stack=67108864 \
    -v `pwd`:/workspace \
    llm-api:pytorch \
    python api/app.py \
    --port 6006 \
    --allow-credentials \
    --model_name chatglm \
    --model_path /data0/models/chatglm-6b \
    --device cuda \
    --embedding_name /data0/models/m3e-base
```
报错：
```
2023-06-18 16:36:45.162 | INFO     | __main__:<module>:463 - args: Namespace(adapter_model_path=None, allow_credentials=True, allowed_headers=['*'], allowed_methods=['*'], allowed_origins=['*'], device='cuda', embedding_name='/data0/models/m3e-base', gpus=None, host='0.0.0.0', load_in_4bit=False, load_in_8bit=False, model_name='chatglm', model_path='/data0/models/chatglm-6b', num_gpus=1, port=6006, quantize=16, stream_interval=2, use_ptuning_v2=False)
Traceback (most recent call last):
  File "api/app.py", line 465, in <module>
    model, tokenizer = load_model(
  File "/workspace/api/models.py", line 231, in load_model
    model, tokenizer = adapter.load_model(
  File "/workspace/api/models.py", line 73, in load_model
    tokenizer = self.tokenizer_class.from_pretrained(model_name_or_path, **tokenizer_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/tokenization_auto.py", line 643, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/tokenization_auto.py", line 487, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/data0/models/chatglm-6b'. Use `repo_type` argument if needed.
```
/data0/models/chatglm-6b 目录有效，其它应用可以正常加载并使用模型

**Comment by xusenlinzy** [comment]
您好，docker命令里面是挂载当前目录
```
-v `pwd`:/workspace
```
您的模型没有放进容器里面去，使用 `-v /data0/models:/workspace/models` 挂载模型，修改后的docker命令应该是
```
docker run -it -d --gpus 2 --ipc=host --net=bridge -p 6006:6006 --name=chatglm \
    --ulimit memlock=-1 --ulimit stack=67108864 \
    -v `pwd`:/workspace \
    -v /data0/models:/workspace/models \ 
    llm-api:pytorch \
    python api/app.py \
    --port 6006 \
    --allow-credentials \
    --model_name chatglm \
    --model_path models/chatglm-6b \
    --device cuda \
    --embedding_name models/m3e-base
```
