### ISSUE TITLE
启动报错  TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by zhouzhou0322** [xusenlinzy/api-for-open-llm#98]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

启动命令 | Startup command

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
# Paste the runtime code here (delete the code block if you don't have it)
```
root@08b6d9bd17b0:/workspace# python api/server.py
2023-08-30 06:44:38.422 | DEBUG    | api.config:<module>:124 - Config: {'HOST': '0.0.0.0', 'PORT': 8000, 'MODEL_NAME': 'baichuan-13b-chat', 'MODEL_PATH': '/share/models/Downloads/Baichuan-13B-Chat', 'ADAPTER_MODEL_PATH': None, 'DEVICE': 'cuda', 'DEVICE_MAP': 'auto', 'GPUS': '', 'NUM_GPUs': 4, 'EMBEDDING_NAME': None, 'EMBEDDING_SIZE': None, 'EMBEDDING_DEVICE': 'cuda', 'QUANTIZE': 16, 'LOAD_IN_8BIT': False, 'LOAD_IN_4BIT': False, 'USING_PTUNING_V2': False, 'CONTEXT_LEN': None, 'STREAM_INTERVERL': 2, 'PROMPT_NAME': None, 'PATCH_TYPE': None, 'ALPHA': 'auto', 'API_PREFIX': '/v1', 'USE_VLLM': False, 'TRUST_REMOTE_CODE': False, 'TOKENIZE_MODE': 'auto', 'TENSOR_PARALLEL_SIZE': 1, 'DTYPE': 'half', 'GPU_MEMORY_UTILIZATION': 0.9, 'MAX_NUM_BATCHED_TOKENS': 5120, 'MAX_NUM_SEQS': 256, 'USE_STREAMER_V2': False, 'API_KEYS': None, 'ACTIVATE_INFERENCE': True}
Traceback (most recent call last):
  File "api/server.py", line 2, in <module>
    from api.models import EMBEDDED_MODEL, GENERATE_MDDEL, app, VLLM_ENGINE
  File "/workspace/api/models.py", line 8, in <module>
    from api.apapter import get_prompt_adapter
  File "/workspace/api/apapter/__init__.py", line 1, in <module>
    from api.apapter.conversation import get_prompt_adapter
  File "/workspace/api/apapter/conversation.py", line 4, in <module>
    from api.utils.protocol import Role, ChatMessage
  File "/workspace/api/utils/protocol.py", line 103, in <module>
    class ChatCompletionResponseChoice(BaseModel):
  File "pydantic/main.py", line 198, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 661, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/usr/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```
root@08b6d9bd17b0:/workspace# python api/server.py
2023-08-30 06:44:38.422 | DEBUG    | api.config:<module>:124 - Config: {'HOST': '0.0.0.0', 'PORT': 8000, 'MODEL_NAME': 'baichuan-13b-chat', 'MODEL_PATH': '/share/models/Downloads/Baichuan-13B-Chat', 'ADAPTER_MODEL_PATH': None, 'DEVICE': 'cuda', 'DEVICE_MAP': 'auto', 'GPUS': '', 'NUM_GPUs': 4, 'EMBEDDING_NAME': None, 'EMBEDDING_SIZE': None, 'EMBEDDING_DEVICE': 'cuda', 'QUANTIZE': 16, 'LOAD_IN_8BIT': False, 'LOAD_IN_4BIT': False, 'USING_PTUNING_V2': False, 'CONTEXT_LEN': None, 'STREAM_INTERVERL': 2, 'PROMPT_NAME': None, 'PATCH_TYPE': None, 'ALPHA': 'auto', 'API_PREFIX': '/v1', 'USE_VLLM': False, 'TRUST_REMOTE_CODE': False, 'TOKENIZE_MODE': 'auto', 'TENSOR_PARALLEL_SIZE': 1, 'DTYPE': 'half', 'GPU_MEMORY_UTILIZATION': 0.9, 'MAX_NUM_BATCHED_TOKENS': 5120, 'MAX_NUM_SEQS': 256, 'USE_STREAMER_V2': False, 'API_KEYS': None, 'ACTIVATE_INFERENCE': True}
Traceback (most recent call last):
  File "api/server.py", line 2, in <module>
    from api.models import EMBEDDED_MODEL, GENERATE_MDDEL, app, VLLM_ENGINE
  File "/workspace/api/models.py", line 8, in <module>
    from api.apapter import get_prompt_adapter
  File "/workspace/api/apapter/__init__.py", line 1, in <module>
    from api.apapter.conversation import get_prompt_adapter
  File "/workspace/api/apapter/conversation.py", line 4, in <module>
    from api.utils.protocol import Role, ChatMessage
  File "/workspace/api/utils/protocol.py", line 103, in <module>
    class ChatCompletionResponseChoice(BaseModel):
  File "pydantic/main.py", line 198, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 661, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/usr/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```
root@08b6d9bd17b0:/workspace# python api/server.py
2023-08-30 06:44:38.422 | DEBUG    | api.config:<module>:124 - Config: {'HOST': '0.0.0.0', 'PORT': 8000, 'MODEL_NAME': 'baichuan-13b-chat', 'MODEL_PATH': '/share/models/Downloads/Baichuan-13B-Chat', 'ADAPTER_MODEL_PATH': None, 'DEVICE': 'cuda', 'DEVICE_MAP': 'auto', 'GPUS': '', 'NUM_GPUs': 4, 'EMBEDDING_NAME': None, 'EMBEDDING_SIZE': None, 'EMBEDDING_DEVICE': 'cuda', 'QUANTIZE': 16, 'LOAD_IN_8BIT': False, 'LOAD_IN_4BIT': False, 'USING_PTUNING_V2': False, 'CONTEXT_LEN': None, 'STREAM_INTERVERL': 2, 'PROMPT_NAME': None, 'PATCH_TYPE': None, 'ALPHA': 'auto', 'API_PREFIX': '/v1', 'USE_VLLM': False, 'TRUST_REMOTE_CODE': False, 'TOKENIZE_MODE': 'auto', 'TENSOR_PARALLEL_SIZE': 1, 'DTYPE': 'half', 'GPU_MEMORY_UTILIZATION': 0.9, 'MAX_NUM_BATCHED_TOKENS': 5120, 'MAX_NUM_SEQS': 256, 'USE_STREAMER_V2': False, 'API_KEYS': None, 'ACTIVATE_INFERENCE': True}
Traceback (most recent call last):
  File "api/server.py", line 2, in <module>
    from api.models import EMBEDDED_MODEL, GENERATE_MDDEL, app, VLLM_ENGINE
  File "/workspace/api/models.py", line 8, in <module>
    from api.apapter import get_prompt_adapter
  File "/workspace/api/apapter/__init__.py", line 1, in <module>
    from api.apapter.conversation import get_prompt_adapter
  File "/workspace/api/apapter/conversation.py", line 4, in <module>
    from api.utils.protocol import Role, ChatMessage
  File "/workspace/api/utils/protocol.py", line 103, in <module>
    class ChatCompletionResponseChoice(BaseModel):
  File "pydantic/main.py", line 198, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 661, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/usr/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class

**Comment by xusenlinzy** [comment]
试一下安装fastapi==0.95.1

**Comment by zhouzhou0322** [comment]
> 试一下安装fastapi==0.95.1

目前就是fastapi==0.95.1 是docker 启动的

.env 是这样的

PORT=8000

# model related
MODEL_NAME=baichuan-13b-chat
MODEL_PATH=/share/models/Downloads/Baichuan-13B-Chat
DEVICE_MAP=auto

# device related
DEVICE=cuda
NUM_GPUs=4

# api related
API_PREFIX=/v1

USE_STREAMER_V2=false

**Comment by zhouzhou0322** [comment]
typing_extensions==4.4.0 这个降级到4.4.0可以 了 nvidia ngc的默认版本是4.7.1
