### ISSUE TITLE
baichuan 13b 部署后 使用langchain调用报错 

### ISSUE THREAD

**Issue by zhouzhou0322** [xusenlinzy/api-for-open-llm#99]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

模型推理和部署 | Model inference and deployment

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

调用脚本
import os

os.environ["OPENAI_API_BASE"] = "http://localhost:7891/v1"
os.environ["OPENAI_API_KEY"] = "xxx"

from langchain.chat_models import ChatOpenAI
from langchain.schema import HumanMessage

chat = ChatOpenAI()
print(chat([HumanMessage(content="你好")]))

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/workspace/api/routes/chat.py", line 98, in create_chat_completion
    content = GENERATE_MDDEL.generate_gate(gen_params)
  File "/workspace/api/generation/core.py", line 155, in generate_gate
    for x in self.generate_stream_gate(params):
  File "/workspace/api/generation/core.py", line 86, in generate_stream_gate
    yield from self.generate_stream_gate_v1(params)
  File "/workspace/api/generation/core.py", line 93, in generate_stream_gate_v1
    for output in self.generate_stream_func(
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 43, in generator_context
    response = gen.send(None)
  File "/workspace/api/generation/stream.py", line 91, in generate_stream
    out = model(torch.as_tensor([input_ids], device=device), use_cache=True)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1423, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/Baichuan-13B-Chat/modeling_baichuan.py", line 447, in forward
    outputs = self.model(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1423, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/Baichuan-13B-Chat/modeling_baichuan.py", line 316, in forward
    alibi_mask = self.get_alibi_mask(inputs_embeds, seq_length_with_past)
  File "/root/.cache/huggingface/modules/transformers_modules/Baichuan-13B-Chat/modeling_baichuan.py", line 276, in get_alibi_mask
    mask = self.future_mask[:self.n_head, :seq_length_with_past, :seq_length_with_past]
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1504, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'BaichuanModel' object has no attribute 'future_mask'

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```

**Comment by xusenlinzy** [comment]
看起来像是文件的问题，试试下载最新的https://huggingface.co/baichuan-inc/Baichuan-13B-Chat/resolve/main/modeling_baichuan.py

**Comment by zhouzhou0322** [comment]
> 看起来像是文件的问题，试试下载最新的https://huggingface.co/baichuan-inc/Baichuan-13B-Chat/resolve/main/modeling_baichuan.py

有办法手动改模型文件的地址吗  目前我设置了model_path 但是解释模型文件的时候好像还是去了默认路径/root/.cache/huggingface/modules/transformers_modules/Baichuan-13B-Chat/modeling_baichuan.py

**Comment by xusenlinzy** [comment]
你把这个缓存的文件删掉试试？

**Comment by zhouzhou0322** [comment]
删掉还是自动下载的 不会加载我指定model_path目录内的modeling_Baichuan

**Comment by zhouzhou0322** [comment]
> 看起来像是文件的问题，试试下载最新的https://huggingface.co/baichuan-inc/Baichuan-13B-Chat/resolve/main/modeling_baichuan.py

换了这个新的modeling_baichuan 现在可以回复了。为什么在root/.cache这里面下载的旧版和我之前下模型的一样 却不能运行了。 是这个future_mask 之前就没有实现吗，官网的cli_run之前也都可以跑通的啊
